### PR TITLE
TST: enable timeout config in playwright notebook test

### PR DESCRIPTION
**Pull request by fangchenli**
## Reference Issues or PRs
xref #1971 #1958 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Any other comments?
The `timeout` or (`runtime`) parameter was not passed to the inner functions, so the playwright test was always using the default value (120 seconds).

### CODE REVIEW

**Comment by iameskild** [comment]
Thanks for working on this @fangchenli! I know this test can be flaky at times but I think I would prefer increasing the timeout instead of labeling this as xfail.

**Review by iameskild — APPROVED** [review]
Thanks @fangchenli! Can you update the branch and when CI passes, feel free to merge!

**Review by iameskild — COMMENTED** [review]
This looks great @fangchenli! I think eventually we want to move these playwright tests to the `tests_integration` directory so we can retire Cypress . How much trouble would it be to make that update?

**Comment by fangchenli** [comment]
@iameskild Thanks for reviewing this PR!

**Pull request merged**
