### PR TITLE
added ability to control the prompt colour

### PR DESCRIPTION
**Pull request by swastik959**
## Reference Issues or PRs
#2023

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by iameskild** [comment]
Hi @swastik959, thanks for working on this! Unfortunately I believe the original issue is asking for control over the color for the `nebari` CLI: https://github.com/nebari-dev/nebari/tree/develop/src/_nebari/subcommands

**Review by iameskild — CHANGES_REQUESTED** [review]
Hi @swastik959, thanks for working on this! Unfortunately I believe the original issue is asking for control over the color for the `nebari` CLI: https://github.com/nebari-dev/nebari/tree/develop/src/_nebari/subcommands

I also believe some of the changes related to the Google Cloud python API made it into this PR. They should probably be removed from here since they seem to be captured in your other PR: https://github.com/nebari-dev/nebari/pull/2083

**Comment by swastik959** [comment]
@iameskild can you tell me where exactly is the color coding for the cli is

**Comment by viniciusdc** [comment]
Hi @swastik959, the Nebari CLI is built using typer, which uses rich underlying to print the color and markup contents. I assume we could have an extra field `--disable-color` for the terminal command args, which could toggle the `color_system` feature for the Console object [here](https://rich.readthedocs.io/en/stable/console.html#color-systems) that's used across Nebari, you can find its mention here for example:

https://github.com/nebari-dev/nebari/blob/cac52efaee70ac0487121b4d6f623766f27d3b30/src/_nebari/cli.py#L44-L52

If I am right, passing the `Console` object in the`Typer` class above is possible.

**Pull request closed without merging**
