### PR TITLE
pytest:ensure failure on warnings

### PR DESCRIPTION
**Pull request by costrouc**
This PR will revert changes that were introduced in the extension branch being merged. Ignoring warnings and especially deprecation warnings in the tests will only lead to problems down the line

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [X] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by iameskild** [comment]
Closing in favor of #1908

**Comment by pmeier** [comment]
@iameskild #1908 is merged and does not contain the diff from this PR or something similar. Did I miss anything or should we reopen?

**Comment by costrouc** [comment]
Re-opened and updated PR to run latest on develop

**Review by pmeier — APPROVED** [review]
CI is green so this LGTM. Thanks @costrouc!

**Pull request merged**
