### PR TITLE
Add support dask-gateway custom cluster config - WIP

### PR DESCRIPTION
**Pull request by viniciusdc**
Fixes | Closes | Resolves #

> Please remove anything marked as optional that you don't need to fill in.
> Choose one of the keywords preceding to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666).
> If there is no issue, remove the line. Remove this note after reading.

## Changes introduced in this PR:

- This PR adds the ability to pass a list of docker images to the cluster configuration selection for spawning the dask workers
- This also includes the ability to add extra volume mounts and volumes to the worker pod
- as well as a toggle option to disable the `scheduler_cmd` and `worker_cmd` bash requirements

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [ ] Yes
- [ ] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [ ] No

## Documentation

Does your contribution include breaking changes or deprecations?
If so have you updated the documentation?

- [ ] Yes, docstrings
- [ ] Yes, main documentation
- [ ] Yes, deprecation notices

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and more.

### CODE REVIEW

**Comment by iameskild** [comment]
Hey @viniciusdc, thanks for opening this PR! Do you think this is something that we can include in our December release (`2022.12.1`)?

**Comment by viniciusdc** [comment]
Hi @iameskild, yes, that's possible. I want to keep this PR, though, as this branch is quite important.

**Comment by iameskild** [comment]
Thanks @viniciusdc! I updated the target branch (to `release/2022.12.1`) so that's why we see those merge conflicts. Let me know if and how I can help :)

**Comment by viniciusdc** [comment]
Thanks, @iameskild. I ended up forgetting about this open PR. I will need to think about how I will handle this a little bit, will try to follow back on this by EoW

**Comment by pavithraes** [comment]
@viniciusdc Mentioned in the weekly sync that we can close this PR, but we need to keep `support_cluster_config_images` branch open because some users depend on it.

**Pull request closed without merging**
