### PR TITLE
Add fix, enhancements and pytests for CLI

### PR DESCRIPTION
**Pull request by iameskild**
~Fixes | Closes | Resolves #~ Related to https://github.com/Quansight/qhub/issues/1478

> Please remove anything marked as optional that you don't need to fill in.
> Choose one of the keywords preceding to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666).
> If there is no issue, remove the line. Remove this note after reading.

## Changes introduced in this PR:

-

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### Requires testing

- [x] Yes
- [ ] No

### In case you checked yes, did you write tests?

- [x] Yes
- [ ] No

## Documentation

Does your contribution include breaking changes or deprecations?
If so have you updated the documentation?

- [x] Yes, docstrings
- [ ] Yes, main documentation
- [ ] Yes, deprecation notices

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and more.

### CODE REVIEW

**Comment by iameskild** [comment]
Blocked by #1501

**Comment by viniciusdc** [comment]
@iameskild is this ready for review?

**Comment by iameskild** [comment]
@trallard @viniciusdc @aktech this PR is ready for review. 

We currently still have the old CLI in the codebase, it think we can remove it in another PR, what are your thoughts?

**Comment by viniciusdc** [comment]
silly request here, but can we modify the name of this test to `PyTest & Formatting`? It took me a while to remember where pytest was running...
https://github.com/nebari-dev/nebari/actions/runs/3336080683/workflow#L30

**Comment by iameskild** [comment]
@viniciusdc I ended up just removing the `black` and `flake8` steps since both of these are being called in the pre-commit action. How does that work for you?

**Review by viniciusdc — APPROVED** [review]
Fantastic!! thanks @iameskild

**Pull request merged**
