### PR TITLE
Modify JupyterHub networkPolicy to match existing policy

### LINKED ISSUE #1965: [BUG] - JupyterHub 3 failing on Digital Ocean
### Describe the bug

Jupyterhub seems unreachable (Service Unavailable) but other services (except for dask-gateway) are available at their respective endpoints. Whats more, the hub pod logs don't seem to show anything wrong and I can run `http://localhost:8081/hub/api` successfully from within the running pod.

### Expected behavior

JupyterHub should be running.

### OS and architecture in which you are running Nebari

Deploy from MacOS

### How to Reproduce the problem?

Deploy Nebari on Digital Ocean from the `develop` branch.

### Command output

_No response_

### Versions and dependencies used.

_No response_

### Compute environment

Digital Ocean

### Integrations

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iameskild**
## What does this implement/fix?

Fixes #1965 

Having the CHP networkPolicy enabled for JupyterHub deployed to AWS, Azure and GCP was no trouble so I'm not sure why this only seems to affect Digital Ocean. We also have the networkPolicy disabled for `hub` and `singleuser` already. 

We should definitely test this change on the other clouds before merging - I don't expect this to cause problems since removing the network policy makes internal networking more permissible.

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by iameskild** [comment]
@costrouc do you see any reason why we shouldn't disabled the `chp.networkPolicy`?

**Review by sblair-metrostar — APPROVED** [review]
lgtm

**Comment by iameskild** [comment]
@pavithraes @kcpevey could you please review?

**Review by pavithraes — APPROVED** [review]
Thanks!

**Pull request merged**
