### PR TITLE
revert breaking change to azure deployment test

### PR DESCRIPTION
**Pull request by Adam-D-Lewis**
## Reference Issues or PRs
https://github.com/nebari-dev/nebari/pull/2632 removed a few credentials on the Azure deployment test which now fails with
```
Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
```
This PR reverts the changes to the credentials.  

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## How to test this PR?
If [this](https://github.com/nebari-dev/nebari/actions/runs/10706057961/job/29682871900) finishes successfully then it verifies this is the fix for the issue.

### CODE REVIEW

**Comment by Adam-D-Lewis** [comment]
Okay, the re-run failed, but the error looked like it was due to it being run from a branch and not develop.  I'd like to merge and see if it runs successfully.

**Comment by Adam-D-Lewis** [comment]
I think we should merge and test, if it still fails, then revert.

**Comment by viniciusdc** [comment]
@Adam-D-Lewis can we trigger the Azure workflow from this branch as a test?

**Review by viniciusdc — APPROVED** [review]
LGTM, This is a quick fix to test the OIDC changes, I am also not against keeping these in here as the global skip var should avoid these requirments showing up on forked repos as well.

**Comment by Adam-D-Lewis** [comment]
Looks like the reason it failed before it tests is that the OIDC login only works from the develop branch currently.

**Pull request merged**
