### PR TITLE
Fix Existing dashboards

### PR DESCRIPTION
**Pull request by Adam-D-Lewis**
## Reference Issues or PRs
Closes https://github.com/nebari-dev/nebari/issues/1127
Fixes Traefik, Keycloak, and Conda Store Dashboards

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by dharhas** [comment]
Are there any graphs that show breakdown by user:
- all the jupyter pods that are in use tagged by username
- the dask workers tagged by username
- argo pods tagged by user name 
etc

**Comment by iameskild** [comment]
This is great, thanks @Adam-D-Lewis! My initial attempt at deploying this failed but I think it didn't include the most recent keycloak changes so I merged `develop` into your branch and I'll try again.

(Also just as an FYI, you might want to update your `git config` on your local machine, at the moment it looks like a blank user made these changes; see the black circle next to your commits. This happened to me earlier this year when I changed the email associated with GitHub)

**Comment by Adam-D-Lewis** [comment]
| (Also just as an FYI, you might want to update your git config on your local machine, at the moment it looks like a blank user made these changes; see the black circle next to your commits. This happened to me earlier this year when I changed the email associated with GitHub)

Thanks for the heads up, @iameskild

**Review by iameskild — APPROVED** [review]
This looks great to me! I was able to get it deployed on an existing cluster and played around with it for a bit. 

I know that the conda-store admin panel tracks this as well (though perhaps not as accurately) but I was glad to see the conda-store volume storage amount here:
Screenshot 2023-04-13 at 16 16 47

Thanks @Adam-D-Lewis :)

**Pull request merged**
