### PR TITLE
AWS gov cloud support

### PR DESCRIPTION
**Pull request by sblair-metrostar**
## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Review by costrouc — COMMENTED** [review]
@sblair-metrostar thanks for this PR. Outside of govcloud will `aws_partition` be equal to `aws`?

**Comment by pavithraes** [comment]
@sblair-metrostar Thanks for this PR! I see this is your first contribution - welcome! ✨ 

@costrouc Thanks for reviewing, can we approve this PR and merge?

**Comment by iameskild** [comment]
The kubernetes test is now passing. It was failing due to the recent flurry of changes to the jupyterlab image (for the scipy tutorials). The images have been restored to working order and the kubernetes test is now passing!

**Comment by iameskild** [comment]
@costrouc @sblair-metrostar is there anything else that needs to be included in this PR? Otherwise, it looks like it can be merged.

**Comment by sblair-metrostar** [comment]
> @costrouc @sblair-metrostar is there anything else that needs to be included in this PR? Otherwise, it looks like it can be merged.

No this should be ready. I can deploy this branch to our govcloud account and get you guys access if there are any additional manual tests you'd like to perform.

**Review by costrouc — APPROVED** [review]

**Pull request merged**
