### PR TITLE
Fix test using a non-specific selector

### LINKED ISSUE #2473: [BUG] - Playwright tests are currently failing due to change in jupyter
### Describe the bug

Fix the tests so they pass.

### Expected behavior

tests should pass

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

See above

### Command output

_No response_

### Versions and dependencies used.

_No response_

### Compute environment

None

### Integrations

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by krassowski**
## Reference Issues or PRs

Fixes #2473

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

## Any other comments?

Let's hope the CI passes!

### CODE REVIEW

**Comment by krassowski** [comment]
Cypress tests are now passing but playwright tests are failing due to the new popup dialog layout:

image

**Comment by krassowski** [comment]
I believe that the cypress/playwright tests are fine, but the deployments tests are failing:

```
_____________________ ERROR at setup of test_dask_gateway ______________________
Traceback (most recent call last):
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/site-packages/urllib3/connectionpool.py", line [46](https://github.com/nebari-dev/nebari/actions/runs/9177179471/job/25234168892?pr=2475#step:20:47)7, in _make_request
    self._validate_conn(conn)
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/site-packages/urllib3/util/ssl_.py", line [50](https://github.com/nebari-dev/nebari/actions/runs/9177179471/job/25234168892?pr=2475#step:20:51)9, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/ssl.py", line [51](https://github.com/nebari-dev/nebari/actions/runs/9177179471/job/25234168892?pr=2475#step:20:52)7, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/home/runnerx/miniconda3/envs/test/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)
```


```
ERROR tests/tests_deployment/test_dask_gateway.py::test_dask_gateway - requests.exceptions.SSLError: HTTPSConnectionPool(host='github-actions.nebari.dev', port=443): Max retries exceeded with url: /hub/api/users/test-user/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
ERROR tests/tests_deployment/test_dask_gateway.py::test_dask_gateway_cluster_options - requests.exceptions.SSLError: HTTPSConnectionPool(host='github-actions.nebari.dev', port=443): Max retries exceeded with url: /hub/api/users/test-user/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
ERROR tests/tests_deployment/test_jupyterhub_ssh.py::test_simple_jupyterhub_ssh - requests.exceptions.SSLError: HTTPSConnectionPool(host='github-actions.nebari.dev', port=443): Max retries exceeded with url: /hub/api/users/test-user/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
ERROR tests/tests_deployment/test_jupyterhub_ssh.py::test_print_jupyterhub_ssh - requests.exceptions.SSLError: HTTPSConnectionPool(host='github-actions.nebari.dev', port=443): Max retries exceeded with url: /hub/api/users/test-user/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
ERROR tests/tests_deployment/test_jupyterhub_ssh.py::test_exact_jupyterhub_ssh - requests.exceptions.SSLError: HTTPSConnectionPool(host='github-actions.nebari.dev', port=443): Max retries exceeded with url: /hub/api/users/test-user/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
ERROR tests/tests_deployment/test_jupyterhub_ssh.py::test_contains_jupyterhub_ssh - requests.exceptions.SSLError: HTTPSConnectionPool(host='github-actions.nebari.dev', port=443): Max retries exceeded with url: /hub/api/users/test-user/tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')))
```

I am also seeing this error in https://github.com/nebari-dev/argo-jupyter-scheduler/pull/10#issuecomment-2122616224. Any ideas on what might be the issue?

Otherwise I think this PR is ready for review.

**Comment by viniciusdc** [comment]
I wonder why this only showed up now... thanks for raising the issue @krassowski

**Comment by Adam-D-Lewis** [comment]
I was able to track this down to our version of requests changed from 2.31.0 to 2.32.2 recently which contains a fix for a bug that was making our tests pass previously (https://github.com/psf/requests/blob/main/HISTORY.md#2320-2024-05-20).

**Review by Adam-D-Lewis — APPROVED** [review]

**Comment by viniciusdc** [comment]
> The bug was making our tests pass previously
Ha, that's funny! Nice catch @Adam-D-Lewis, great work @krassowski

**Pull request merged**
