### PR TITLE
upgrade instructions for PR 2453

### PR DESCRIPTION
**Pull request by Adam-D-Lewis**
## Reference Issues or PRs
This is a companion PR to https://github.com/nebari-dev/nebari/pull/2453.  B/c we don't yet know for sure the next version of Nebari will be 2024.5.2, I've added this PR to be corrected and merged shortly before the next release of Nebari.

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by Adam-D-Lewis** [comment]
@marcelovilla I'm fine with the updates!

**Comment by viniciusdc** [comment]
@Adam-D-Lewis @marcelovilla any updates on this? can we commit these suggestion and re-test?

**Comment by marcelovilla** [comment]
@viniciusdc I just commited the suggestions. I was hoping to use this PR to include the instructions for upgrading Grafana as well but we can split it in multiple PRs if it makes more sense. Anyway, this should be included in the official release but not necessarily on the RCs, right?

**Comment by marcelovilla** [comment]
I'm merging this in order to release a candidate that includes the upgrade step for the GCP default nodes. Once https://github.com/nebari-dev/nebari/pull/2472 is merged, I'll open a PR updating the step with relevant information about the actions that need to be taken.

**Review by marcelovilla — APPROVED** [review]

**Pull request merged**
