### PR TITLE
CI: add azure integration

### PR DESCRIPTION
**Pull request by fangchenli**
## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [x] Did you add new tests?

### CODE REVIEW

**Comment by iameskild** [comment]
I think you're encountering the same issue I did when I last attempted to update Azure to use OIDC: https://github.com/nebari-dev/nebari/issues/1694

**Comment by dcmcand** [comment]
@viniciusdc can you take a look at this and see if you can pick this up?

**Comment by Adam-D-Lewis** [comment]
Looks like it's working now and should be ready for review @viniciusdc @marcelovilla

**Comment by Adam-D-Lewis** [comment]
LGTM!

**Review by Adam-D-Lewis — APPROVED** [review]

**Comment by aktech** [comment]
Is this intended to run on every pull request?

**Comment by Adam-D-Lewis** [comment]
> Is this intended to run on every pull request?

@aktech No, the intent is just to run weekly with the others.  I can fix later today or feel free to fix if desired.

**Comment by Adam-D-Lewis** [comment]
Fixed now - https://github.com/nebari-dev/nebari/pull/2498#event-13002430072

**Comment by aktech** [comment]
Awesome, thanks! 🎉

**Pull request merged**
