### PR TITLE
Add "Open VS Code" entry in services

### PR DESCRIPTION
**Pull request by krassowski**
## Reference Issues or PRs

Together with https://github.com/nebari-dev/jupyterlab-nebari-mode/pull/1 fixes https://github.com/nebari-dev/nebari/issues/2217

## What does this implement/fix?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

See integration tests in https://github.com/nebari-dev/jupyterlab-nebari-mode/pull/1.

## Any other comments?

-

### CODE REVIEW

**Comment by krassowski** [comment]
This can be tested with a docker image including `jupyterlab-nebari-mode==0.2.0`, and should be safe to merge even for users of docker images which do not include `jupyterlab-nebari-mode` because because when the command is not available the added menu item will simply not show up (without any side effects).

**Comment by marcelovilla** [comment]
@krassowski should we pin `jupyterlab-nebari-mode` to `0.2.0` in https://github.com/nebari-dev/nebari-docker-images/blob/main/jupyterlab/environment.yaml and then start upgrading as we release new versions?

**Review by marcelovilla — APPROVED** [review]

**Comment by krassowski** [comment]
Thanks! I opened https://github.com/nebari-dev/nebari-docker-images/pull/123

**Comment by krassowski** [comment]
Is it ok to merge this one?

**Comment by marcelovilla** [comment]
@krassowski yes, let's merge it so it makes the next release

**Pull request merged**
