### PR TITLE
Add Grafana Loki integration

### PR DESCRIPTION
**Pull request by aktech**
## Reference Issues or PRs
#2104 

I have bumped CI machine to `t3a.2xlarge` as we're deploying few more resources and previous machine was bit too small for that.

Documentation PR: https://github.com/nebari-dev/nebari-docs/pull/416
Docs preview: https://deploy-preview-416--nebari-docs.netlify.app/docs/how-tos/monitoring

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [X] Did you test the pull request locally?
- [X] Did you add new tests?

### CODE REVIEW

**Comment by aktech** [comment]
CI failure is due to https://github.com/nebari-dev/nebari/issues/2285

**Comment by aktech** [comment]
Added node selectors.

**Comment by aktech** [comment]
>LGTM, I would just include an optional variable to control the deployment of minio, in case the user wants to use the override option to pass an S3 bucket for storage and we don't deploy a resource it will not be using.

Yep make sense, made minio optional now.

> it might be interesting to expand the UI testing with playwright to showcase a query

This is going to me more involved that's why I added a test to fetch logs from API to make sure it works. I totally agree this would be very useful. How do you feel about we do it in a follow up PR?

**Comment by viniciusdc** [comment]
Completely agree.

**Review by viniciusdc — APPROVED** [review]
LGTM, thanks @aktech

**Pull request merged**
