### PR TITLE
Add middleware to prefix JupyterHub navbar items with /hub.

### LINKED ISSUE #2359: [BUG] - JupyterHub navbar items not redirecting correctly after visiting Admin Dashboard
### Describe the bug

Nebari borrows some navbar items from JupyterHub, such as the Home, Token and Admin tabs. These work fine until one goes to the Admin tab. After visiting the Admin Dashboard, trying to go back to any of the Home, Token, and even the Admin tabs result in a `404 page not found error`. Here is an example of the Token tab, before and after visiting the Admin Dashboard:

https://github.com/nebari-dev/nebari/assets/36754005/df30e9cb-0f35-457f-864e-580aa49c15cd

As you can see, the Token tab URL is `/hub/token` before visiting the Admin Dashboard, but becomes `/token` after that.

I can reproduce this behavior (i.e. URLs changing after visiting the Admin Dashboard; see lower left corner in the video) locally using vanilla JupyterHub, with the difference that redirection works fine:

https://github.com/nebari-dev/nebari/assets/36754005/f5039655-ef57-4205-9c96-a257d43002ed

I guess we can have Nebari redirect `/token` to `/hub/token` but we would need to make sure that's not a general rule, as other services don't have the `/hub` prefix. For example: `/conda-store`.

### Expected behavior

I would expect for users to be able to go to the Admin Dashboard and then navigate back successfully to other sections of JupyterHub (e.g., the Home or Token tabs).

### OS and architecture in which you are running Nebari

AWS

### How to Reproduce the problem?

1. Visit the Admin Dashboard at `/hub/admin`
2. Try to navigate to one of the Home, Token or Admin tabs.

### Command output

_No response_

### Versions and dependencies used.

Nebari `2024.3.2`

### Compute environment

None

### Integrations

_No response_

### Anything else?

This issue was originally identified by @kalpanachinnappan.

### PR DESCRIPTION
**Pull request by marcelovilla**
## Reference Issues or PRs

Closes #2359 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by marcelovilla** [comment]
I ran into an issue when trying to apply these changes in an existing deployment, having Terraform yield the following error:

```
[terraform]: │ Error: There was a field manager conflict when trying to apply the manifest for "dev/jupyterhub"
[terraform]: │
[terraform]: │   with module.jupyterhub.kubernetes_manifest.jupyterhub,
[terraform]: │   on modules/kubernetes/services/jupyterhub/main.tf line 214, in resource "kubernetes_manifest" "jupyterhub":
[terraform]: │  214: resource "kubernetes_manifest" "jupyterhub" {
[terraform]: │
[terraform]: │ The API returned the following conflict: "Apply failed with 1 conflict:
[terraform]: │ conflict with \"kubectl-edit\" using traefik.containo.us/v1alpha1:
[terraform]: │ .spec.routes"
[terraform]: │
[terraform]: │ You can override this conflict by setting "force_conflicts" to true in the
[terraform]: │ "field_manager" block.
```

I was able to manually delete the manifest in the k8s cluster and then the `nebari deploy` worked.

@viniciusdc should I add the `field_manager` block as suggested or do you think there's a better approach?

**Comment by viniciusdc** [comment]
I had some issues running nebari today, so I will be able to test this only tomorrow morning, but in the mean time, as part of out testing overhaul mindset, it might be interesting to add a cypress test for this:
visit admin -> visit any other page
if the test passes then this is fixed

**Comment by marcelovilla** [comment]
@viniciusdc I did and it works just fine. You are right, the error message was because we were manually editing the configuration on that deployment.

**Review by viniciusdc — APPROVED** [review]
LGTM, thanks for the amazing work @marcelovilla -- as soon as the tests finishes we can merge this

**Comment by marcelovilla** [comment]
> as part of out testing overhaul mindset, it might be interesting to add a cypress test for this: visit admin -> visit any other page if the test passes then this is fixed

I agree it might make sense to add some specific tests for this kind of workflows (or user journeys) but if it's ok with you, I would prefer doing so after we have finished the discussion on how to structure our tests in the future.

**Pull request merged**
