### PR TITLE
PR: Update dashboard environment

### PR DESCRIPTION
**Pull request by ppwadhwa**
Updates the dashboard environment to pinned versions of most packages.  All examples can be launched via cds dashboards.

## Reference Issues or PRs
Addresses https://github.com/kcpevey/nebari_work/issues/3

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by kcpevey** [comment]
Can you confirm all the new dashboard examples work with this environment?

**Comment by ppwadhwa** [comment]
I did confirm they work with all the new examples.  I can check again, but they deployed with cds dashboards.

**Comment by kcpevey** [comment]
Adding @viniciusdc and @iameskild (whichever gets to it first) for one final look before merging

**Review by iameskild — APPROVED** [review]
Thanks @ppwadhwa :)

**Pull request merged**
