### PR TITLE
Block usage of pip inside jupyterlab 

### LINKED ISSUE #2133: Isolate .local (i.e. pip) installations for each environment
### Feature description

Currently, if I pip install a package into a conda env from the command line, the packages get added to my private `.local` space. However, if I have a second environment which does the same thing, THOSE get added to the `.local` space as well. This creates a situation where the pip packages from BOTH environments are now available in BOTH environments. 

The real kicker is that if the second environment required different versions of the pip packages, it goes ahead and updates the `.local`, leaving the first environment in a broken state. 

This happens very much behind the scenes and users have no idea what happened to their first environment since they "didn't touch it". 

We should isolate the pip installed packages so that there is no cross-contamination between environments. 

### Value and/or benefit

Clean, isolated environments that pip can't break and happy users :) 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by viniciusdc**
## Reference Issues or PRs

closes #2133 

## What does this implement/fix?

This update adds a blocking configuration (globally applied) to the pip command, where its usage will only be habilitated if the user uses a ` virtualenv,` which we can assume the user will not attempt as we already provide the conda environments for such needs.

As an environment variable controls this, it's still possible to be overridden by the user if the variable's value is modified.

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

## Any other comments?
Tested within a local deployment:

- from within a notebook:
image
- from terminal:
image

obs.: tested within all envs to make sure it was supplied as a global update

### CODE REVIEW

**Comment by costrouc** [comment]
@viniciusdc have you tested this PR out locally to see if this works?

**Comment by costrouc** [comment]
Updating branch to rerun ci

**Comment by viniciusdc** [comment]
> @viniciusdc have you tested this PR out locally to see if this works?

Tested locally, screenshots in the description

**Review by costrouc — APPROVED** [review]
LGTM! Thanks @viniciusdc for testing this out. Playwright is failing due to jupyterlab ui changes that do not affect this PR.

**Pull request merged**
