### PR TITLE
Validate instance types for GCP

### PR DESCRIPTION
**Pull request by blakerosenthal**
## Reference Issues or PRs

Closes https://github.com/nebari-dev/nebari/issues/2718

Adds back the `instances(region:str)` function to the GCP provider and validates available instances against the nebari config.

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

## How to test this PR?

Check out and install this branch, then follow the instructions to [deploy nebari on GCP](https://www.nebari.dev/docs/how-tos/nebari-gcp/). Run `nebari validate -c nebari-config.yaml` to validate available instance types.

### CODE REVIEW

**Comment by blakerosenthal** [comment]
@marcelovilla It looks like I'm missing a `GOOGLE_CREDENTIALS` environment variable in the tests. I spent some time with the test code trying to understand this but there's a lot of things that are instantiated at runtime. Is it obvious to you what's failing here?

https://github.com/nebari-dev/nebari/actions/runs/10948510295/job/30399687802?pr=2730

**Comment by marcelovilla** [comment]
@blakerosenthal I'll take a look at this tomorrow! Thanks for working on this 🚀

**Review by dcmcand — CHANGES_REQUESTED** [review]
@blakerosenthal can you please add a pytest mock to the fixture at https://github.com/nebari-dev/nebari/blob/215bbd622f0ea1692e79bb4411db81ef28b1d329/tests/tests_unit/conftest.py#L92 for `google_cloud.instances` to allow the unit tests to pass without needing to hit the actual gcp endpoints?

**Comment by dcmcand** [comment]
@blakerosenthal if you have a moment, can you update the tests for this?

**Review by dcmcand — APPROVED** [review]

**Pull request merged**
