### PR TITLE
nebari upgrade CLI tests

### LINKED ISSUE #1961: [BUG] - nebari upgrade incorrect image matching on profiles.dask_worker
### Describe the bug

`nebari upgrade` is incorrectly expecting the `profiles.dask_worker` section to have a `kubespawner_override` subsection for image tag updates. Per the schema, the `image` value should be at the top level of the named profile.

### Expected behavior

Command should successfully upgrade any matching image tags included in the `profiles.dask_worker` section to the current release.

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

Run `nebari upgrade -c nebari-config.yaml` on a file with something like the following present:

Image will be found in the following (incorrect) yaml:
``` yaml

profiles:
  dask_worker:
    test:
      kubespawner_override:
        image: quay.io/nebari/nebari-jupyterlab:2023.4.1

```

Image will be missed in the following (correct) yaml:
``` yaml

profiles:
  dask_worker:
    test:
      image: quay.io/nebari/nebari-jupyterlab:2023.4.1

```

### Command output

_No response_

### Versions and dependencies used.

Nebari: 2023.7.2.dev

### Compute environment

None

### Integrations

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1962: [BUG] - nebari upgrade doesn't match -gpu images
### Describe the bug

Running `nebari upgrade` fails to find/upgrade included gpu images when searching for tags to upgrade to the current version. Ex: `quay.io/nebari/nebari-jupyterlab-gpu:2023.5.1` will get skipped, but `quay.io/nebari/nebari-jupyterlab:2023.5.1` will trigger an upgrade prompt.

### Expected behavior

All [valid nebari image tags](https://quay.io/organization/nebari) should be matched and trigger the associated upgrade behavior.

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

Run `nebari upgrade -c nebari-config.yaml` on a file with something like the following present:

``` yaml

project_name: test
provider: local
domain: test.example.com
namespace: dev
nebari_version: 2023.4.1
profiles:
  jupyterlab:
  - display_name: test
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab:2023.4.1
  - display_name: test-gpu
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab-gpu:2023.4.1

```

### Command output

``` yaml

project_name: test
provider: local
domain: test.example.com
namespace: dev
nebari_version: 2023.7.2
profiles:
  jupyterlab:
  - display_name: test
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab:2023.7.2
  - display_name: test-gpu
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab-gpu:2023.4.1

```

### Versions and dependencies used.

Nebari: 2023.7.2.dev

### Compute environment

None

### Integrations

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sblair-metrostar**
## Reference Issues or PRs

#1862 

Fixes #1961 
Fixes #1962

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Other (please describe): Unit tests

## Testing

- [x] Did you test the pull request locally?
- [x] Did you add new tests?

### CODE REVIEW

**Review by iameskild — CHANGES_REQUESTED** [review]
Thanks @sblair-metrostar for these tests! 

I currently see four tests failing. One is a `test_upgrade_does_nothing_on_same_version` and the other three appear to be tests written for the 0.4.0 upgrade. For the old 0.4.0 upgrade tests, I would be alright if we tore those out given how old they are and I don't think the maintenance burden is worth it.

**Comment by sblair-metrostar** [comment]
@iameskild I've updated the details of #1961. There was a bug with that behavior but wasn't what I thought it was initially.

**Review by iameskild — APPROVED** [review]
Thanks for the fixes @sblair-metrostar! 

One question I forgot to ask earlier was around new releases. Before cut a new release, we need add a new `Upgrade_` class and, with these changes, we should also add another test for that upgrade. Is that how you were also envisioning this?

**Comment by sblair-metrostar** [comment]
> Thanks for the fixes @sblair-metrostar!
> 
> One question I forgot to ask earlier was around new releases. Before cut a new release, we need add a new `Upgrade_` class and, with these changes, we should also add another test for that upgrade. Is that how you were also envisioning this?

That would be my expectation, yes. There's some quirkiness around whether or not there's a release specific UpgradeStep in nebari or not and a few tests that only work with the "current" version we'll want to keep an eye on. But we should just be able to add a test that covers the 7.2 to 9.1 upgrade path with any specific yaml assertions we'd expect in addition to the version getting ticked up.

**Comment by iameskild** [comment]
Related to https://github.com/nebari-dev/nebari/issues/1955

**Pull request merged**
