### PR TITLE
Test pyproject dependencies can be built by conda

### PR DESCRIPTION
**Pull request by iameskild**
## Reference Issues or PRs

We recently decided that we should pin as many dependencies as possible to avoid problems that arise for breaking changes (as has happened before). Part of that work includes pinning the python dependencies we have in the `pyproject.toml`. However, given that we release Nebari to PyPI and Conda-Forge, we need to make sure that the package can be built by both package managers (see this [nebari-feedstock PR](https://github.com/conda-forge/nebari-feedstock) for what happens when there are dependency conflicts).

This PR creates a simple test that pulls the required package dependencies from the `pyproject.toml`, creates an `environment.yaml` and then tries to build it. If it fails, it is because there is dependency conflict coming from conda-forge and we should update our `pyproject.toml` accordingly.

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [x] Other (please describe): tests

## Testing

- [x] Did you test the pull request locally?
- [x] Did you add new tests?

### CODE REVIEW

**Comment by viniciusdc** [comment]
Hi @iameskild, thanks for opening this PR. I noticed though that you added a ''parser/compiler'' for reading the Nebari pip dependencies into a conda unable environment. While that does help, I am concerned that it might not suffice for future testing due to:
- We will need to constantly maintain the different package name inconsistencies (e.g. `python-kubernetes`)

**Comment by viniciusdc** [comment]
for running in dev (e.g a local branch or on CI)

**Comment by viniciusdc** [comment]
I got the following requirement error: 
```
export SRC_DIR=/home/vcerutti/miniconda3/envs/nebari/conda-bld/nebari_1677181748620/test_tmp
import: 'nebari'
import: 'nebari'
+ pip check
python-keycloak 2.12.0 has requirement requests-toolbelt<0.10.0,>=0.9.1, but you have requests-toolbelt 0.10.1.
Tests failed for nebari-2023.1.2.dev5+g4923b690-py_0.tar.bz2 - moving package to /home/vcerutti/miniconda3/envs/nebari/conda-bld/broken

```
came from `pip check` so at least the build succeeded with the new pins :)

**Comment by iameskild** [comment]
Thank you so much for the review @viniciusdc! I hadn't heard of Greyskull before but I will look into getting this working as you described :)

**Pull request closed without merging**
