### PR TITLE
remove execute permissions on templates

### PR DESCRIPTION
**Pull request by pmeier**
## What does this implement/fix?

While working on #1778, I reached a state where the exclude in

https://github.com/nebari-dev/nebari/blob/8bd56f90b84c7686f45459ae8f7cf690721bd60a/.pre-commit-config.yaml#L36-L37

did not apply. With that, `pre-commit` showed me three files that had execute permissions but no shebang. Given that these are templates and no other template has execute permissions and a shebang, I've just removed the execute permissions here.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by Adam-D-Lewis** [comment]
Seems fine, but it'd be nice to run a k8s test, just to be sure.

**Review by costrouc — APPROVED** [review]
Weird those had execute permissions. Thanks for fixing that.

**Pull request merged**
