### PR TITLE
Add config option to enable the encryption of AWS EKS secrets

### PR DESCRIPTION
**Pull request by joneszc**
## Reference Issues or PRs
Fixes [#2681](https://github.com/nebari-dev/nebari/issues/2681)

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

### Allows user to set EKS encryption of secrets by specifying a KMS key ARN in nebari-config.yaml
```
amazon_web_services:
  eks_kms_arn: 'arn:aws:kms:us-east-1:010101010:key/3xxxxxxx-xxxxx-xxxxx-xxxxx'
```
image

### The KMS key must meet the following conditions:
* Symmetric
* Can encrypt and decrypt data
* Created in the same AWS Region as the cluster
* If the KMS key was created in a different account, the [IAM principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html#iam-term-principal) must have access to the KMS key.

### CODE REVIEW

**Review by kenafoster — APPROVED** [review]
LGTM but if this is merged we should open up a nebari-docs since it's a little tricky to implement and understand

I've confirmed that most of the mistakes you could make (wrong region, bad format, key doesn't exist or Nebari deploy user can't see it) will fail in the stage where it creates the IAM policy, so at least it won't get to modifying the EKS cluster before failing

**Comment by viniciusdc** [comment]
I would say that we could have a validator in the AWS Pydantic provider (similar to how we already do for the instance types and region) so that the feedback loop in case of errors is quicker for the user doing the deployment (instead of relying on terraform only for the "check").

**Comment by joneszc** [comment]
> I would say that we could have a validator in the AWS Pydantic provider (similar to how we already do for the instance types and region) so that the feedback loop in case of errors is quicker for the user doing the deployment (instead of relying on terraform only for the "check").

@viniciusdc @tylergraff 
As suggested, I have added initial kms-key arn validation steps [here](https://github.com/MetroStar/nebari/commit/e13fdb311e0889601488ebe35d77951c8a49ba3c)
I'm still testing these updates

**Comment by joneszc** [comment]
> I think the issues with the tests below are due to the recent move from `develop` to `main`. Can you update your fork repo and update this branch?

@viniciusdc,
This [branch](https://github.com/MetroStar/nebari/tree/eks-cluster-encryption) is now, at time of writing, up to date with nebari-dev/nebari:main.  Does this suffice with your recommended action or are we still missing something? Thanks!

**Comment by joneszc** [comment]
> I think the issues with the tests below are due to the recent move from `develop` to `main`. Can you update your fork repo and update this branch?

@viniciusdc,
This [branch](https://github.com/MetroStar/nebari/tree/eks-cluster-encryption) should now, at time of writing, be up to date with nebari-dev/nebari:main. Thanks!

**Comment by joneszc** [comment]
Restoring [branch](https://github.com/MetroStar/nebari/tree/eks-cluster-encryption)

**Pull request closed without merging**
