### PR TITLE
add cloud provider deployment status badges to README.md

### PR DESCRIPTION
**Pull request by Adam-D-Lewis**
## Reference Issues or PRs
You can see the new badges at https://github.com/nebari-dev/nebari/tree/depl-badges

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by Adam-D-Lewis** [comment]
Ready for review!

**Comment by Adam-D-Lewis** [comment]
> Also, I noticed that the badge for DO says GCP in there because our DO tests have the same name as the GCP one in the workflow file 🤣

This PR will fix that naming issue.  I think it'll only show up on that preview page after merge though.

**Comment by Adam-D-Lewis** [comment]
> This is nice, thanks, @Adam-D-Lewis. I don't see any problems with integrating this right away, but I am curious if we want to first make the DO and Azure tests pass again.

I say we merge without fixing.  It'll give us motivation to fix those others soon.

**Review by viniciusdc — APPROVED** [review]
Sounds good to me, thanks @Adam-D-Lewis

**Review by viniciusdc — APPROVED** [review]

**Pull request merged**
