### PR TITLE
Make conda-store file system read-only by default

### PR DESCRIPTION
**Pull request by alimanfoo**
This a small suggestion, but I'd suggest making the conda-store file system read-only by default. This will prevent users accidentally modifying environments created via conda-store by running pip install or conda install from their server.

### CODE REVIEW

**Comment by pavithraes** [comment]
@alimanfoo Thanks for opening this PR!

**Review by iameskild — APPROVED** [review]
I've tested this on an existing deployment and I didn't run into any issues. I created a few new conda-store envs and had no trouble using them.

@costrouc do you have any objection to merging this?

**Review by costrouc — APPROVED** [review]
@iameskild look great to me and ready for merge!

**Pull request merged**
