### PR TITLE
Feature remove jupyterlab news

### PR DESCRIPTION
**Pull request by costrouc**
Remove the following popup

image

```shell
jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
```

and

```json
{
    "@jupyterlab/apputils-extension:notification": {
        "fetchNews": "false"
    }
}
```

### CODE REVIEW

**Review by iameskild — APPROVED** [review]
Nice 😎

**Comment by trallard** [comment]
The PR needs testing and needs someone to verify that this is actually doing what it should be doing

**Comment by viniciusdc** [comment]
https://jupyterlab.readthedocs.io/en/stable/user/announcements.html

https://jupyterlab.readthedocs.io/en/stable/user/binder.html

**Comment by viniciusdc** [comment]
Tested on locally, changes are successfully propagated: 
image

It's worth mentioning that the extension responsible for those pop-ups is only present in the recent main* version of the jupyterlab docker image. 

[*] quay.io/nebari/nebari-jupyterlab@sha256:ce52205cc2dde5c62a4db8931c11fff46f281c78a4c1523d2a646dd7edecf65c

**Review by viniciusdc — APPROVED** [review]
Working as expected

**Comment by trallard** [comment]
This has been approved for a while, shall this be merged @costrouc?

**Comment by costrouc** [comment]
Yes. I was trying to avoid merging my own PR. Will merge now

**Pull request merged**
