### PR TITLE
Set `launch_template.ami_id` attrs to private

### PR DESCRIPTION
**Pull request by viniciusdc**
This PR will disable the configuration of `node_groups.*.launch_template.ami_id` specifically, until #2832 is addressed. 

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by viniciusdc** [comment]
Checking pydantic docs to be sure this is the correct setting

**Comment by viniciusdc** [comment]
This is what the validation error will look like if the user tries to pass the `ami_id` field 
image

The reason for not completely removing it, is that once the error on the terraform side of things is addressed, we can just re-enable this field instead of re-including

**Comment by viniciusdc** [comment]
just waiting for the tests

**Review by dcmcand — APPROVED** [review]
:tada:

**Pull request merged**
