### PR TITLE
Enable authentication by default in jupyter-server

### PR DESCRIPTION
**Pull request by krassowski**
## Reference Issues or PRs

- Relates to https://github.com/nebari-dev/nebari/issues/2241
- Depends on https://github.com/nebari-dev/nebari-docker-images/pull/124
- Depends on https://github.com/nebari-dev/nebari/pull/2286 to work too

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by krassowski** [comment]
Sorry, I forgot to undraft once the other PRs got merged. I think we should give it a try.

**Comment by marcelovilla** [comment]
@krassowski tests are failing with:

First Test -- Check Nebari login and start JupyterLab (failed)

Can't check the full event log, though. Anything comes to mind?

**Comment by krassowski** [comment]
Back to draft. I need to make a PR to jupyterhub.

**Comment by krassowski** [comment]
https://github.com/jupyterhub/jupyterhub/pull/4779 was merged, we will need to wait with this one for a new JupyterHub release

**Comment by krassowski** [comment]
With JupyterHub 5 in we should be able to make progress here.

**Comment by krassowski** [comment]
By which I meant that this is ready to go into the next release (maybe not the upcoming one yet, but let's merge is ASAP after the release is out).

**Review by marcelovilla — APPROVED** [review]

**Comment by marcelovilla** [comment]
Thanks @krassowski ! Now that the release is out, should we merge this for the next one?

**Comment by krassowski** [comment]
Yes, thank you for remembering about it!

**Pull request merged**
