### PR TITLE
Update secret token in release-notes-sync action

### PR DESCRIPTION
**Pull request by pavithraes**
## Reference Issues or PRs

#1751

## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by pavithraes** [comment]
@iameskild - `@kcpevey` created this token in https://github.com/nebari-dev/nebari/pull/1634/files#diff-6049d8683a0b46dba1b0692c5d9a342381f0a016cf9c1e76a9059d3eb9cd6105R51

So, I think this should work?

**Review by iameskild — APPROVED** [review]
@pavithraes reading through the action README, we need to ensure the token is a PAT - which looks like it is in this PR. I say we make this change and I can test that this is resolved by creating a `dev` pre-release.

**Comment by pavithraes** [comment]
@iameskild Thank you, I'll merge! We can also trigger it with a dispatch event -- I can try this immediately. :)

**Comment by pavithraes** [comment]
@iameskild -- It worked! 
* https://github.com/nebari-dev/nebari/actions/runs/4819302976
* https://github.com/nebari-dev/nebari-docs/pull/317

**Pull request merged**
