### PR TITLE
[ENH] Move Vault secrets and provider auth to custom action

### PR DESCRIPTION
**Pull request by viniciusdc**
## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [ ] Did you test the pull request locally?
- [ ] Did you add new tests?

### CODE REVIEW

**Comment by marcelovilla** [comment]
@viniciusdc is this ready for review? Is there an associated issue?

**Comment by marcelovilla** [comment]
@viniciusdc with Vault failing relatively frequently, I'm wondering if we should consider just using GitHub secrets instead. Any thoughts?

C.C. @Adam-D-Lewis @dcmcand

**Comment by dcmcand** [comment]
I would be in favor of moving away from vault

**Comment by marcelovilla** [comment]
I opened https://github.com/nebari-dev/nebari/issues/2835

**Comment by marcelovilla** [comment]
We're going to address https://github.com/nebari-dev/nebari/issues/2835 so we won't be merging this PR

**Pull request closed without merging**
